// AUTO-GENERATED by scripts/fetch-symbols.ts — do not edit by hand.
// Symbols: Mulberry Symbol Set, CC BY-SA 4.0 (https://mulberrysymbols.org).

export type SymbolCategory = "people" | "places" | "activities" | "feelings" | "food";

export type SymbolEntry = {
  id: string;
  label: string;
  category: SymbolCategory;
  file: string;
};

export const SYMBOLS: readonly SymbolEntry[] = [
  { id: "mom", label: "Mom", category: "people", file: "/symbols/mom.svg" },
  { id: "sister", label: "Sister", category: "people", file: "/symbols/sister.svg" },
  { id: "aunt", label: "Aunt", category: "people", file: "/symbols/aunt.svg" },
  { id: "family", label: "Family", category: "people", file: "/symbols/family.svg" },
  { id: "dog", label: "Dog", category: "people", file: "/symbols/dog.svg" },
  { id: "grandma", label: "Grandma", category: "people", file: "/symbols/grandma.svg" },
  { id: "home", label: "Home", category: "places", file: "/symbols/home.svg" },
  { id: "cafe", label: "Cafe", category: "places", file: "/symbols/cafe.svg" },
  { id: "shop", label: "Shop", category: "places", file: "/symbols/shop.svg" },
  { id: "outside", label: "Outside", category: "places", file: "/symbols/outside.svg" },
  { id: "beach", label: "Beach", category: "places", file: "/symbols/beach.svg" },
  { id: "school", label: "School", category: "places", file: "/symbols/school.svg" },
  { id: "swim", label: "Swim", category: "activities", file: "/symbols/swim.svg" },
  { id: "walk", label: "Walk", category: "activities", file: "/symbols/walk.svg" },
  { id: "draw", label: "Draw", category: "activities", file: "/symbols/draw.svg" },
  { id: "read", label: "Read", category: "activities", file: "/symbols/read.svg" },
  { id: "eat", label: "Eat", category: "activities", file: "/symbols/eat.svg" },
  { id: "music", label: "Music", category: "activities", file: "/symbols/music.svg" },
  { id: "happy", label: "Happy", category: "feelings", file: "/symbols/happy.svg" },
  { id: "sad", label: "Sad", category: "feelings", file: "/symbols/sad.svg" },
  { id: "excited", label: "Excited", category: "feelings", file: "/symbols/excited.svg" },
  { id: "calm", label: "Calm", category: "feelings", file: "/symbols/calm.svg" },
  { id: "worried", label: "Worried", category: "feelings", file: "/symbols/worried.svg" },
  { id: "surprised", label: "Surprised", category: "feelings", file: "/symbols/surprised.svg" },
  { id: "pizza", label: "Pizza", category: "food", file: "/symbols/pizza.svg" },
  { id: "ice-cream", label: "Ice cream", category: "food", file: "/symbols/ice-cream.svg" },
  { id: "watermelon", label: "Watermelon", category: "food", file: "/symbols/watermelon.svg" },
  { id: "apple", label: "Apple", category: "food", file: "/symbols/apple.svg" },
  { id: "sandwich", label: "Sandwich", category: "food", file: "/symbols/sandwich.svg" },
  { id: "hot-chocolate", label: "Hot chocolate", category: "food", file: "/symbols/hot-chocolate.svg" },
];

export const SYMBOL_CATEGORIES: readonly SymbolCategory[] = [
  "people",
  "places",
  "activities",
  "feelings",
  "food",
];

export const SYMBOLS_BY_ID: Readonly<Record<string, SymbolEntry>> = Object.fromEntries(
  SYMBOLS.map((s) => [s.id, s]),
);
