// Downloads a curated subset of Mulberry symbols (CC BY-SA 4.0) into public/symbols/
// and writes src/data/symbols.ts. Idempotent: skips files already on disk.
//
// Run:  npm run fetch:symbols

import { mkdir, writeFile, access } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SYMBOLS_DIR = resolve(ROOT, "public/symbols");
const MANIFEST_PATH = resolve(ROOT, "src/data/symbols.ts");

const RAW_BASE =
  "https://raw.githubusercontent.com/mulberrysymbols/mulberry-symbols/master/EN";

type Category = "people" | "places" | "activities" | "feelings" | "food";

type Entry = {
  id: string;          // stable, kebab-cased local id (used in code + manifest)
  label: string;       // user-facing label rendered on the button
  category: Category;
  source: string;      // Mulberry filename without .svg
};

// Curated to match the synthetic profile: some have profile matches (good for
// grounded citations), others have no match (demo of "stay general" guardrail).
const SYMBOLS: Entry[] = [
  // PEOPLE
  { id: "mom", label: "Mom", category: "people", source: "mum_parent" },
  { id: "sister", label: "Sister", category: "people", source: "sister" },
  { id: "aunt", label: "Aunt", category: "people", source: "aunt_maternal" },
  { id: "family", label: "Family", category: "people", source: "family" },
  { id: "dog", label: "Dog", category: "people", source: "dog" },
  { id: "grandma", label: "Grandma", category: "people", source: "grandmother" },

  // PLACES
  { id: "home", label: "Home", category: "places", source: "house" },
  { id: "cafe", label: "Cafe", category: "places", source: "cafe" },
  { id: "shop", label: "Shop", category: "places", source: "shop" },
  { id: "outside", label: "Outside", category: "places", source: "outside" },
  { id: "beach", label: "Beach", category: "places", source: "beach" },
  { id: "school", label: "School", category: "places", source: "school" },

  // ACTIVITIES
  { id: "swim", label: "Swim", category: "activities", source: "swim_,_to" },
  { id: "walk", label: "Walk", category: "activities", source: "walk_,_to" },
  { id: "draw", label: "Draw", category: "activities", source: "draw_,_to" },
  { id: "read", label: "Read", category: "activities", source: "read_,_to" },
  { id: "eat", label: "Eat", category: "activities", source: "eat_,_to" },
  { id: "music", label: "Music", category: "activities", source: "music" },

  // FEELINGS (Mulberry only ships gendered feeling symbols; we use one consistent
  // illustration style and a neutral text label so the button reads as the feeling)
  { id: "happy", label: "Happy", category: "feelings", source: "happy_lady" },
  { id: "sad", label: "Sad", category: "feelings", source: "sad_lady" },
  { id: "excited", label: "Excited", category: "feelings", source: "excited_lady" },
  { id: "calm", label: "Calm", category: "feelings", source: "serene_lady" },
  { id: "worried", label: "Worried", category: "feelings", source: "worried_lady" },
  { id: "surprised", label: "Surprised", category: "feelings", source: "surprised_lady" },

  // FOOD
  { id: "pizza", label: "Pizza", category: "food", source: "pizza" },
  { id: "ice-cream", label: "Ice cream", category: "food", source: "ice_cream" },
  { id: "watermelon", label: "Watermelon", category: "food", source: "watermelon" },
  { id: "apple", label: "Apple", category: "food", source: "apple" },
  { id: "sandwich", label: "Sandwich", category: "food", source: "sandwich" },
  { id: "hot-chocolate", label: "Hot chocolate", category: "food", source: "hot_chocolate" },
];

async function fileExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function fetchSvg(name: string): Promise<string> {
  const url = `${RAW_BASE}/${encodeURIComponent(name)}.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status} for ${url}`);
  const text = await res.text();
  if (!text.trimStart().startsWith("<svg") && !text.trimStart().startsWith("<?xml")) {
    throw new Error(`${name}: response is not SVG`);
  }
  return text;
}

function manifestTs(entries: Entry[]): string {
  const lines = entries
    .map(
      (e) =>
        `  { id: ${JSON.stringify(e.id)}, label: ${JSON.stringify(e.label)}, category: ${JSON.stringify(e.category)}, file: ${JSON.stringify(`/symbols/${e.id}.svg`)} },`,
    )
    .join("\n");
  return `// AUTO-GENERATED by scripts/fetch-symbols.ts — do not edit by hand.
// Symbols: Mulberry Symbol Set, CC BY-SA 4.0 (https://mulberrysymbols.org).

export type SymbolCategory = "people" | "places" | "activities" | "feelings" | "food";

export type SymbolEntry = {
  id: string;
  label: string;
  category: SymbolCategory;
  file: string;
};

export const SYMBOLS: readonly SymbolEntry[] = [
${lines}
];

export const SYMBOL_CATEGORIES: readonly SymbolCategory[] = [
  "people",
  "places",
  "activities",
  "feelings",
  "food",
];

export const SYMBOLS_BY_ID: Readonly<Record<string, SymbolEntry>> = Object.fromEntries(
  SYMBOLS.map((s) => [s.id, s]),
);
`;
}

async function main() {
  await mkdir(SYMBOLS_DIR, { recursive: true });
  await mkdir(dirname(MANIFEST_PATH), { recursive: true });

  let downloaded = 0;
  let skipped = 0;
  const failures: string[] = [];

  for (const entry of SYMBOLS) {
    const dest = resolve(SYMBOLS_DIR, `${entry.id}.svg`);
    if (await fileExists(dest)) {
      skipped++;
      continue;
    }
    try {
      const svg = await fetchSvg(entry.source);
      await writeFile(dest, svg, "utf8");
      downloaded++;
      process.stdout.write(`  ✓ ${entry.id} (${entry.source}.svg)\n`);
    } catch (err) {
      failures.push(`${entry.id} <- ${entry.source}: ${(err as Error).message}`);
    }
  }

  await writeFile(MANIFEST_PATH, manifestTs(SYMBOLS), "utf8");

  console.log(
    `\nDone. downloaded=${downloaded} skipped=${skipped} failed=${failures.length}`,
  );
  if (failures.length) {
    console.log("\nFailures:");
    failures.forEach((f) => console.log(`  - ${f}`));
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
